-- Migration: 069_update_quran_surah_names_ug.sql
-- Description: Update Quran surah names in Uyghur to standard spelling from dinhayat.com
-- Author: Antigravity
-- Date: 2026-07-12

BEGIN;

UPDATE public.quran SET surah_name_ug = CASE surah
    WHEN 1 THEN 'فاتىھە'
    WHEN 2 THEN 'بەقەرە'
    WHEN 3 THEN 'ئال ئىمران'
    WHEN 4 THEN 'نىسا'
    WHEN 5 THEN 'مائىدە'
    WHEN 6 THEN 'ئەنئام'
    WHEN 7 THEN 'ئەئراف'
    WHEN 8 THEN 'ئەنفال'
    WHEN 9 THEN 'تەۋبە'
    WHEN 10 THEN 'يۇنۇس'
    WHEN 11 THEN 'ھۇد'
    WHEN 12 THEN 'يۈسۈف'
    WHEN 13 THEN 'رەئد'
    WHEN 14 THEN 'ئىبراھىم'
    WHEN 15 THEN 'ھىجر'
    WHEN 16 THEN 'نەھل'
    WHEN 17 THEN 'ئىسرا'
    WHEN 18 THEN 'كەھف'
    WHEN 19 THEN 'مەريەم'
    WHEN 20 THEN 'تاھا'
    WHEN 21 THEN 'ئەنبىيا'
    WHEN 22 THEN 'ھەج'
    WHEN 23 THEN 'مۇئمىنۇن'
    WHEN 24 THEN 'نۇر'
    WHEN 25 THEN 'فۇرقان'
    WHEN 26 THEN 'شۇئەرا'
    WHEN 27 THEN 'نەمل'
    WHEN 28 THEN 'قەسەس'
    WHEN 29 THEN 'ئەنكەبۇت'
    WHEN 30 THEN 'رۇم'
    WHEN 31 THEN 'لۇقمان'
    WHEN 32 THEN 'سەجدە'
    WHEN 33 THEN 'ئەھزاب'
    WHEN 34 THEN 'سەبەئ'
    WHEN 35 THEN 'فاتىر'
    WHEN 36 THEN 'ياسىين'
    WHEN 37 THEN 'ساففات'
    WHEN 38 THEN 'ساد'
    WHEN 39 THEN 'زۇمەر'
    WHEN 40 THEN 'غافىر'
    WHEN 41 THEN 'فۇسسىلەت'
    WHEN 42 THEN 'شۇرا'
    WHEN 43 THEN 'زۇخرۇف'
    WHEN 44 THEN 'دۇخان'
    WHEN 45 THEN 'جاسىيە'
    WHEN 46 THEN 'ئەھقاف'
    WHEN 47 THEN 'مۇھەممەد'
    WHEN 48 THEN 'فەتھ'
    WHEN 49 THEN 'ھۇجۇرات'
    WHEN 50 THEN 'قاف'
    WHEN 51 THEN 'زارىيات'
    WHEN 52 THEN 'تۇر'
    WHEN 53 THEN 'نەجم'
    WHEN 54 THEN 'قەمەر'
    WHEN 55 THEN 'رەھمان'
    WHEN 56 THEN 'ۋاقىئە'
    WHEN 57 THEN 'ھەدىد'
    WHEN 58 THEN 'مۇجادەلە'
    WHEN 59 THEN 'ھەشر'
    WHEN 60 THEN 'مۇمتەھىنە'
    WHEN 61 THEN 'سەف'
    WHEN 62 THEN 'جۇمۇئە'
    WHEN 63 THEN 'مۇنافىقۇن'
    WHEN 64 THEN 'تەغابۇن'
    WHEN 65 THEN 'تەلاق'
    WHEN 66 THEN 'تەھرىم'
    WHEN 67 THEN 'مۇلك'
    WHEN 68 THEN 'قەلەم'
    WHEN 69 THEN 'ھاققە'
    WHEN 70 THEN 'مەئارىج'
    WHEN 71 THEN 'نۇھ'
    WHEN 72 THEN 'جىن'
    WHEN 73 THEN 'مۇززەممىل'
    WHEN 74 THEN 'مۇددەسسىر'
    WHEN 75 THEN 'قىيامەت'
    WHEN 76 THEN 'ئىنسان'
    WHEN 77 THEN 'مۇرسەلات'
    WHEN 78 THEN 'نەبەئ'
    WHEN 79 THEN 'نازىئات'
    WHEN 80 THEN 'ئەبەسە'
    WHEN 81 THEN 'تەكۋىر'
    WHEN 82 THEN 'ئىنفىتار'
    WHEN 83 THEN 'مۇتەففىفين'
    WHEN 84 THEN 'ئىنشىقاق'
    WHEN 85 THEN 'بۇرۇج'
    WHEN 86 THEN 'تارىق'
    WHEN 87 THEN 'ئەئلا'
    WHEN 88 THEN 'غاشىيە'
    WHEN 89 THEN 'فەجر'
    WHEN 90 THEN 'بەلەد'
    WHEN 91 THEN 'شەمس'
    WHEN 92 THEN 'لەيل'
    WHEN 93 THEN 'زۇھا'
    WHEN 94 THEN 'شەرھ'
    WHEN 95 THEN 'تىين'
    WHEN 96 THEN 'ئەلەق'
    WHEN 97 THEN 'قەدر'
    WHEN 98 THEN 'بەييىنە'
    WHEN 99 THEN 'زەلزەلە'
    WHEN 100 THEN 'ئادىيات'
    WHEN 101 THEN 'قارىئە'
    WHEN 102 THEN 'تەكاسۇر'
    WHEN 103 THEN 'ئەسر'
    WHEN 104 THEN 'ھۇمەزە'
    WHEN 105 THEN 'فىل'
    WHEN 106 THEN 'قۇرەيش'
    WHEN 107 THEN 'مائۇن'
    WHEN 108 THEN 'كەۋسەر'
    WHEN 109 THEN 'كافىرۇن'
    WHEN 110 THEN 'نەسر'
    WHEN 111 THEN 'مەسەد'
    WHEN 112 THEN 'ئىخلاس'
    WHEN 113 THEN 'فەلەق'
    WHEN 114 THEN 'ناس'
END;

COMMIT;