"""Shared pipeline step and milestone constants."""

PIPELINE_STEP_OCR = "ocr"
PIPELINE_STEP_CHUNKING = "chunking"
PIPELINE_STEP_EMBEDDING = "embedding"
PIPELINE_STEP_SPELL_CHECK = "spell_check"
PIPELINE_STEP_SUMMARY = "summary"

PIPELINE_ORDER = (
    PIPELINE_STEP_OCR,
    PIPELINE_STEP_CHUNKING,
    PIPELINE_STEP_EMBEDDING,
    PIPELINE_STEP_SPELL_CHECK,
)

PAGE_MILESTONE_IDLE = "idle"
PAGE_MILESTONE_IN_PROGRESS = "in_progress"
PAGE_MILESTONE_SUCCEEDED = "succeeded"
PAGE_MILESTONE_DONE = "done"
PAGE_MILESTONE_FAILED = "failed"
PAGE_MILESTONE_ERROR = "error"

FAILED_PAGE_MILESTONES = (
    PAGE_MILESTONE_FAILED,
    PAGE_MILESTONE_ERROR,
)

BOOK_MILESTONE_IDLE = "idle"
BOOK_MILESTONE_IN_PROGRESS = "in_progress"
BOOK_MILESTONE_COMPLETE = "complete"
BOOK_MILESTONE_PARTIAL_FAILURE = "partial_failure"
BOOK_MILESTONE_FAILED = "failed"

PAGE_MILESTONE_ATTR_BY_STEP = {
    PIPELINE_STEP_OCR: "ocr_milestone",
    PIPELINE_STEP_CHUNKING: "chunking_milestone",
    PIPELINE_STEP_EMBEDDING: "embedding_milestone",
    PIPELINE_STEP_SPELL_CHECK: "spell_check_milestone",
}

BOOK_MILESTONE_ATTR_BY_STEP = PAGE_MILESTONE_ATTR_BY_STEP.copy()

STEP_DONE_MILESTONE_BY_STEP = {
    PIPELINE_STEP_OCR: PAGE_MILESTONE_SUCCEEDED,
    PIPELINE_STEP_CHUNKING: PAGE_MILESTONE_SUCCEEDED,
    PIPELINE_STEP_EMBEDDING: PAGE_MILESTONE_SUCCEEDED,
    PIPELINE_STEP_SPELL_CHECK: PAGE_MILESTONE_DONE,
}
