repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # Run the linter and fix auto-fixable rules (like unused imports)
      - id: ruff
        args: [ --fix, --ignore=E402 ]
      # Run the formatter
      - id: ruff-format
