apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitabim-data-pvc
  namespace: kitabim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
