apiVersion: apps/v1
kind: Deployment
metadata:
  name: uyghurocr
  namespace: kitabim
spec:
  replicas: 0
  selector:
    matchLabels:
      app: uyghurocr
  template:
    metadata:
      labels:
        app: uyghurocr
    spec:
      containers:
        - name: uyghurocr
          image: kitabim-uyghurocr:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: uyghurocr
  namespace: kitabim
spec:
  selector:
    app: uyghurocr
  ports:
    - port: 8001
      targetPort: 8001
