apiVersion: v1
kind: ConfigMap
metadata:
  name: kitabim-config
  namespace: kitabim
data:
  MONGODB_URL: mongodb://mongo:27017
  MONGODB_DATABASE: kitabim_ai_db
  OCR_PROVIDER: local
  LOCAL_OCR_URL: http://uyghurocr:8001
  MAX_PARALLEL_PAGES: "1"
  DATA_DIR: /data
